[general]
import = [
  "~/.config/alacritty/themes/blood-moon.toml"
]

[window]
opacity = 0.5
decorations = "None"
startup_mode = "Fullscreen"
padding = { x = 3, y = 4}

[font]
#size = 17.4 # big ass fonts
size = 10.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italics" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
