backend = "xrender"
vsync = true
use-damage = true

# blur-method = "box"   # lightest blur option
# blur-size = 5         # keep it small
# 
# wintypes:
# {
#   term = { blur-background = true; }
# }
# 
# blur-background-exclude = [
#   "class_g != 'Alacritty'" # blur only in Alacritty
# ]
