backend = "glx"
vsync = true
use-damage = true

blur-method = "box"
blur-size = 5

wintypes:
{
  term = { blur-background = true; }
}

blur-background-exclude = [
  "class_g != 'Alacritty'" # blur only in Alacritty
]
